Traceback (most recent call last):
  File "/home/akhilesh/Academics - Semester II/CS6910 - Deep Learning/CS6910-Deep-Learning/best_model_conf_matrix.py", line 85, in <module>
    wandb.log({"confusion_matrix_figure":wandb.Image(fig)})
  File "/home/akhilesh/.local/lib/python3.10/site-packages/wandb/sdk/data_types/image.py", line 179, in __init__
    self._initialize_from_data(data_or_path, mode, file_type)
  File "/home/akhilesh/.local/lib/python3.10/site-packages/wandb/sdk/data_types/image.py", line 321, in _initialize_from_data
    if data.ndim > 2:
AttributeError: 'function' object has no attribute 'ndim'
Traceback (most recent call last):
  File "/home/akhilesh/Academics - Semester II/CS6910 - Deep Learning/CS6910-Deep-Learning/best_model_conf_matrix.py", line 85, in <module>
    wandb.log({"confusion_matrix_figure":wandb.Image(fig)})
  File "/home/akhilesh/.local/lib/python3.10/site-packages/wandb/sdk/data_types/image.py", line 179, in __init__
    self._initialize_from_data(data_or_path, mode, file_type)
  File "/home/akhilesh/.local/lib/python3.10/site-packages/wandb/sdk/data_types/image.py", line 321, in _initialize_from_data
    if data.ndim > 2:
AttributeError: 'function' object has no attribute 'ndim'